version: '3.8'

services:
  chat-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - OPENAI_API_BASE_URL=
      - OPENAI_API_KEY=
      - AZURE_OPENAI_API_BASE_URL=
      - AZURE_OPENAI_API_KEY=
      - AZURE_OPENAI_DEPLOYMENT=
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}